FROM nginx:alpine

# Copy the custom nginx config
COPY app/nginx.conf /etc/nginx/nginx.conf

# Copy static files directly into the image
COPY app/static /app/static

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
